
package br.com.acorde.view;


import br.com.acorde.dao.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class TelaNutricionistaPerfil extends javax.swing.JInternalFrame {

    //variaveis do BD
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    private void deletarConta(){
        int confirma = JOptionPane.showConfirmDialog(null, "Essa ação deleta sua conta. Deseja continuar?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            String sql = "delete from Nutricionista where IdNutricionista = ?";
            try{
               pst = conexao.prepareStatement(sql);
               pst.setString(1, txtIdNutri.getText());
               int apagado = pst.executeUpdate();
               
               if(apagado > 0){
                 
                  txtIdNutri.setText(null);
                  txtNomeNutri.setText(null);
                  txtEmailNutri.setText(null);
                  jpfSenhaNutri.setText(null);
                  txtSobrenomeNutri.setText(null);
                  ftxtDataNutri.setText(null);
                  ftxCRNNutri.setText(null);
                  jtxTelefoneNutri.setText(null);
                  JOptionPane.showMessageDialog(null, "Sua conta foi apagada.");
                  System.exit(0);
               }
               
            }catch(Exception e){
                 JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }
    
    //implementar o EDITAR CONTA - CODIGO FEITO em TelaEdFisPerfil ou TelaClientePerfil
    /**
     * Creates new form TelaNutricionistaPerfil
     */
    public TelaNutricionistaPerfil() {
         initComponents();
         conexao = ModuloConexao.conexaoBanco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdNutri = new javax.swing.JTextField();
        txtNomeNutri = new javax.swing.JTextField();
        txtSobrenomeNutri = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ftxCRNNutri = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxTelefoneNutri = new javax.swing.JFormattedTextField();
        txtEmailNutri = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jpfSenhaNutri = new javax.swing.JPasswordField();
        lblBotaoDeletarDados = new javax.swing.JLabel();
        lblBotaoEditarDados = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ftxtDataNutri = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Perfil");
        setMinimumSize(new java.awt.Dimension(752, 511));
        setPreferredSize(new java.awt.Dimension(752, 511));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(744, 511));
        jPanel1.setPreferredSize(new java.awt.Dimension(744, 511));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setMinimumSize(new java.awt.Dimension(728, 88));
        jPanel2.setPreferredSize(new java.awt.Dimension(728, 88));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Seus Dados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Id de Nutricionista:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 106, 146, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("*Nome:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 106, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Sobrenome:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 106, -1, -1));

        txtIdNutri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdNutri.setEnabled(false);
        jPanel1.add(txtIdNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 134, 172, -1));

        txtNomeNutri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtNomeNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 134, 159, -1));

        txtSobrenomeNutri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtSobrenomeNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 134, 155, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Data de Nascimento:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 181, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CRN:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 181, -1, -1));

        ftxCRNNutri.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        ftxCRNNutri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(ftxCRNNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 210, 159, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Telefone:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 175, -1, 29));

        try {
            jtxTelefoneNutri.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxTelefoneNutri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtxTelefoneNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 210, 155, -1));

        txtEmailNutri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtEmailNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 172, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("*Email:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 262, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("*Senha:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 262, -1, -1));

        jpfSenhaNutri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jpfSenhaNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 290, 159, -1));

        lblBotaoDeletarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/deletar.png"))); // NOI18N
        lblBotaoDeletarDados.setToolTipText("Deletar Dados");
        lblBotaoDeletarDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotaoDeletarDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotaoDeletarDadosMouseClicked(evt);
            }
        });
        jPanel1.add(lblBotaoDeletarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        lblBotaoEditarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/salvar.png"))); // NOI18N
        lblBotaoEditarDados.setToolTipText("Editar Dados");
        lblBotaoEditarDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblBotaoEditarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Salvar Dados");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 410, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Deletar Dados");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("*Campos Obrigatórios");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        try {
            ftxtDataNutri.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtDataNutri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(ftxtDataNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 752, 511);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBotaoDeletarDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoDeletarDadosMouseClicked
      deletarConta();
    }//GEN-LAST:event_lblBotaoDeletarDadosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JFormattedTextField ftxCRNNutri;
    public static javax.swing.JFormattedTextField ftxtDataNutri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPasswordField jpfSenhaNutri;
    public static javax.swing.JFormattedTextField jtxTelefoneNutri;
    private javax.swing.JLabel lblBotaoDeletarDados;
    private javax.swing.JLabel lblBotaoEditarDados;
    public static javax.swing.JTextField txtEmailNutri;
    public static javax.swing.JTextField txtIdNutri;
    public static javax.swing.JTextField txtNomeNutri;
    public static javax.swing.JTextField txtSobrenomeNutri;
    // End of variables declaration//GEN-END:variables
}
