
package br.com.acorde.view;

import br.com.acorde.dao.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class TelaLogin extends javax.swing.JFrame {

    //variaveis do BD
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public void logar(){
      
      //cabe um fabrica aqui? acho que cabe ein
      //dá um finally pra fechar a conexao com o bd
        if(cbPerfilLogin.getSelectedItem().equals("Cliente")){
             String sql = "select * from cliente where email = ? and senha = ?";
             try{
                pst = conexao.prepareStatement(sql);
                pst.setString(1, tfEmailLogin.getText());
                pst.setString(2, pfSenhaLogin.getText());
                //eecutando a query
                rs = pst.executeQuery();
                if(rs.next()){
                    TelaPrincipalCliente principal = new TelaPrincipalCliente();
                    principal.setVisible(true);
                    //exibe o nome do usuario
                    TelaPrincipalCliente.lblUserNome.setText(rs.getString(2));
                }else{
                    JOptionPane.showMessageDialog(null, "usuario e/ou senha invalido");
                }
             }catch(Exception e){
                 JOptionPane.showMessageDialog(null, e);
                  e.printStackTrace();
             }finally{
                 try {
                     conexao.close();
                 } catch (SQLException ex) {
                     Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
        }else if(cbPerfilLogin.getSelectedItem().equals("Educador Físico")){
            String sql = "select * from educador_fisico where email = ? and senha = ?";
            try{
                pst = conexao.prepareStatement(sql);
                pst.setString(1, tfEmailLogin.getText());
                pst.setString(2, pfSenhaLogin.getText());
                //eecutando a query
                rs = pst.executeQuery();
                if(rs.next()){
                    TelaPrincipalEdFis principal = new TelaPrincipalEdFis();
                    principal.setVisible(true);
                     //exibe o nome do usuario
                    TelaPrincipalEdFis.lblNomeEdFis.setText(rs.getString(2));
                }else{
                    JOptionPane.showMessageDialog(null, "usuario e/ou senha invalido");
                }
             }catch(Exception e){
                 JOptionPane.showMessageDialog(null, e);
                 e.printStackTrace();
             }finally{
                try {
                    conexao.close();
                } catch (SQLException ex) {
                    Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }else{
            String sql = "select * from nutricionista where email = ? and senha = ?";
            try{
                pst = conexao.prepareStatement(sql);
                pst.setString(1, tfEmailLogin.getText());
                pst.setString(2, pfSenhaLogin.getText());
                //eecutando a query
                rs = pst.executeQuery();
                if(rs.next()){
                    TelaPrincipalNutricionista principal = new TelaPrincipalNutricionista();
                    principal.setVisible(true);
                     //exibe o nome do usuario
                    TelaPrincipalNutricionista.lblNomeNutric.setText(rs.getString(2));
                }else{
                    JOptionPane.showMessageDialog(null, "usuario e/ou senha invalido");
                }
             }catch(Exception e){
                 JOptionPane.showMessageDialog(null, e);
                  e.printStackTrace();
             }finally{
                try {
                    conexao.close();
                } catch (SQLException ex) {
                    Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        //fecha a tela de login
        dispose();
    }
    
    //Creates new form TelaLogin
    public TelaLogin() {
        initComponents();
        conexao = ModuloConexao.conexaoBanco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfEmailLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pfSenhaLogin = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        cbPerfilLogin = new javax.swing.JComboBox<>();
        btnLogin = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastre no <Acorde!>");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setText("<Acorde!>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Email:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 129, -1, -1));

        tfEmailLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfEmailLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jPanel1.add(tfEmailLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 152, 222, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Senha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 188, -1, -1));

        pfSenhaLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pfSenhaLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jPanel1.add(pfSenhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 211, 222, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Perfil:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 247, -1, -1));

        cbPerfilLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPerfilLogin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Educador Físico", "Nutricionista" }));
        jPanel1.add(cbPerfilLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 222, -1));

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 329, 91, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 329, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("É novo por aqui?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 391, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cadastre-se");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(418, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        logar();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cbPerfilLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pfSenhaLogin;
    private javax.swing.JTextField tfEmailLogin;
    // End of variables declaration//GEN-END:variables
}
