
package br.com.acorde.view;

import br.com.acorde.dao.ModuloConexao;
import static br.com.acorde.view.TelaEdFisPerfil.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;


public class TelaPrincipalEdFis extends javax.swing.JFrame {
    
     //variaveis do BD
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form TelaPrincipalEdFis
     */
    public TelaPrincipalEdFis() {
        initComponents();
        conexao = ModuloConexao.conexaoBanco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNomeEdFis = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblPerfilEdFis = new javax.swing.JLabel();
        lblEdFisTreino = new javax.swing.JLabel();
        lblEdFisExercicio = new javax.swing.JLabel();
        lblEdFisMsg = new javax.swing.JLabel();
        lblEdFisSair = new javax.swing.JLabel();
        jPanelAreaEdFis = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bem vindo(a) ao <Acorde!>");
        setMinimumSize(new java.awt.Dimension(957, 650));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(947, 650));
        jPanel3.setPreferredSize(new java.awt.Dimension(947, 650));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 131));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 131));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Seja bem vindo(a) ao <Acorde!>, ");

        lblNomeEdFis.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNomeEdFis.setText("Nome");

        lblData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblData.setText("Terça, 23 de Março de 2021");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeEdFis))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNomeEdFis))
                .addGap(18, 18, 18)
                .addComponent(lblData)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setMinimumSize(new java.awt.Dimension(237, 513));
        jPanel2.setPreferredSize(new java.awt.Dimension(237, 513));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Menu");

        lblPerfilEdFis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPerfilEdFis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/user.png"))); // NOI18N
        lblPerfilEdFis.setText("     Perfil");
        lblPerfilEdFis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPerfilEdFisMouseClicked(evt);
            }
        });

        lblEdFisTreino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEdFisTreino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/treino.png"))); // NOI18N
        lblEdFisTreino.setText("    Treino");
        lblEdFisTreino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEdFisTreinoMouseClicked(evt);
            }
        });

        lblEdFisExercicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEdFisExercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/exercicio.png"))); // NOI18N
        lblEdFisExercicio.setText("    Exercício");
        lblEdFisExercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEdFisExercicioMouseClicked(evt);
            }
        });

        lblEdFisMsg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEdFisMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/msg.png"))); // NOI18N
        lblEdFisMsg.setText("    Mensagem");
        lblEdFisMsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEdFisMsgMouseClicked(evt);
            }
        });

        lblEdFisSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEdFisSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/sair.png"))); // NOI18N
        lblEdFisSair.setText("    Sair");
        lblEdFisSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEdFisSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPerfilEdFis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEdFisTreino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(81, 81, 81))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEdFisExercicio)
                    .addComponent(lblEdFisMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEdFisSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(lblPerfilEdFis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEdFisTreino)
                .addGap(13, 13, 13)
                .addComponent(lblEdFisExercicio)
                .addGap(18, 18, 18)
                .addComponent(lblEdFisMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEdFisSair)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jPanelAreaEdFis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelAreaEdFis.setMinimumSize(new java.awt.Dimension(723, 513));
        jPanelAreaEdFis.setPreferredSize(new java.awt.Dimension(723, 513));

        javax.swing.GroupLayout jPanelAreaEdFisLayout = new javax.swing.GroupLayout(jPanelAreaEdFis);
        jPanelAreaEdFis.setLayout(jPanelAreaEdFisLayout);
        jPanelAreaEdFisLayout.setHorizontalGroup(
            jPanelAreaEdFisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        jPanelAreaEdFisLayout.setVerticalGroup(
            jPanelAreaEdFisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelAreaEdFis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAreaEdFis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(973, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //traz a data do sistema
        Date data = new Date();
        DateFormat formatado = DateFormat.getDateInstance(DateFormat.FULL);
        lblData.setText(formatado.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void lblPerfilEdFisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPerfilEdFisMouseClicked
        TelaEdFisPerfil perfilEdFis = new TelaEdFisPerfil();
        perfilEdFis.setVisible(true);
        jPanelAreaEdFis.add(perfilEdFis);
        
        //ao clicar no botao perfil os dados que o cliente cadastrou vai ser mostrado no tela de Perfil
        //tazer conexao com o bd (ok)
        //(((((PROBLEMA)))) SÓ exibe o msm dado sempre
          String sql = "select * from Educador_Fisico";
          try{
              pst = conexao.prepareStatement(sql);
              //pst.setString(1, txtIdCliente.getText());
              rs = pst.executeQuery();
              // rs.last() pega a ultima linha que foi colocada no bd, entao vai ter que fazer cadastro e login
              //para mostrar essas duas funcionalidades e pegar o ultimo que foi cadastrado
              if(rs.last()){
                  txtIdEdFis.setText(rs.getString(1));
                  txtNomeEdFis.setText(rs.getString(2));
                  txtEmailEdFis.setText(rs.getString(3));
                  jpfSenhaEdFis.setText(rs.getString(4));
                  txtSobrenomeEdFis.setText(rs.getString(5));
                  ftxtDataEdFis.setText(rs.getString(6));
                  ftxCREF.setText(rs.getString(7));
                  jtxTelefoneEdFis.setText(rs.getString(8));
              } 
          }catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
              e.printStackTrace();
          }
    }//GEN-LAST:event_lblPerfilEdFisMouseClicked

    private void lblEdFisTreinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEdFisTreinoMouseClicked
        TelaEdFisTreino edFisTreino = new TelaEdFisTreino();
        edFisTreino.setVisible(true);
        jPanelAreaEdFis.add(edFisTreino);
    }//GEN-LAST:event_lblEdFisTreinoMouseClicked

    private void lblEdFisExercicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEdFisExercicioMouseClicked
        TelaEdFisExercicio edFisExercicio = new TelaEdFisExercicio();
        edFisExercicio.setVisible(true);
        jPanelAreaEdFis.add(edFisExercicio);
    }//GEN-LAST:event_lblEdFisExercicioMouseClicked

    private void lblEdFisMsgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEdFisMsgMouseClicked
        TelaEdFisMensagem edFisMsg = new  TelaEdFisMensagem();
       edFisMsg.setVisible(true);
        jPanelAreaEdFis.add(edFisMsg);
    }//GEN-LAST:event_lblEdFisMsgMouseClicked

    private void lblEdFisSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEdFisSairMouseClicked
       int sair = JOptionPane.showConfirmDialog(null, "Deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
           System.exit(0);
        }
    }//GEN-LAST:event_lblEdFisSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalEdFis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalEdFis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalEdFis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalEdFis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalEdFis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAreaEdFis;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEdFisExercicio;
    private javax.swing.JLabel lblEdFisMsg;
    private javax.swing.JLabel lblEdFisSair;
    private javax.swing.JLabel lblEdFisTreino;
    public static javax.swing.JLabel lblNomeEdFis;
    private javax.swing.JLabel lblPerfilEdFis;
    // End of variables declaration//GEN-END:variables
}
