/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.acorde.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Freetech
 */
public class TelaPrincipalCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalCliente
     */
    public TelaPrincipalCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneCliente = new javax.swing.JDesktopPane();
        lblUserNome1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelCliente = new javax.swing.JPanel();
        lblUserNome = new javax.swing.JLabel();
        lblTreino = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTreinoImagem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();
        lblMensagemIcon = new javax.swing.JLabel();
        lblIconUser = new javax.swing.JLabel();
        jMenuBarCliente = new javax.swing.JMenuBar();
        JMenuTabNutric = new javax.swing.JMenu();
        jMenuExercicio = new javax.swing.JMenu();
        jMenuItemExercAnaer = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuGastoCaloria = new javax.swing.JMenu();
        jMenuProgDieta = new javax.swing.JMenu();
        jMenuProfissionais = new javax.swing.JMenu();
        jMenuItemEF = new javax.swing.JMenuItem();
        jMenuItemNutricionista = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seja bem-vindo(a) ao <Acorde!>");
        setResizable(false);

        jDesktopPaneCliente.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPaneCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserNome1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblUserNome1.setForeground(new java.awt.Color(204, 204, 204));
        lblUserNome1.setText("Nome");
        jDesktopPaneCliente.add(lblUserNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 121, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Seja bem vindo(a),");
        jDesktopPaneCliente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 220, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText(" 22 de Março de 2021");
        jDesktopPaneCliente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 150, 20));

        jPanelCliente.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCliente.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jPanelClienteInputMethodTextChanged(evt);
            }
        });

        lblUserNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserNome.setText("Nome");

        lblTreino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTreino.setText("Treino");

        lblTreinoImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/treino.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Dieta");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/prato.png"))); // NOI18N

        lblMensagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMensagem.setText("Mensagem");

        lblMensagemIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/msg.png"))); // NOI18N

        lblIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTreinoImagem)
                            .addComponent(lblTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMensagemIcon))
                        .addGap(70, 70, 70)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanelClienteLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2))))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelClienteLayout.createSequentialGroup()
                                .addComponent(lblIconUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(lblUserNome, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMensagem))))
                .addContainerGap())
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelClienteLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lblIconUser))
                            .addGroup(jPanelClienteLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lblUserNome)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblTreinoImagem))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTreino))
                .addGap(32, 32, 32)
                .addComponent(lblMensagemIcon)
                .addGap(18, 18, 18)
                .addComponent(lblMensagem)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        JMenuTabNutric.setText("Tabela Nutricional    ");
        jMenuBarCliente.add(JMenuTabNutric);

        jMenuExercicio.setText("Exercícios   ");

        jMenuItemExercAnaer.setText("Aeróbico");
        jMenuExercicio.add(jMenuItemExercAnaer);

        jMenuItem2.setText("Anaeróbico");
        jMenuExercicio.add(jMenuItem2);

        jMenuBarCliente.add(jMenuExercicio);

        jMenuGastoCaloria.setText("Gasto de Calorias   ");
        jMenuBarCliente.add(jMenuGastoCaloria);

        jMenuProgDieta.setText("Progresso da Dieta   ");
        jMenuBarCliente.add(jMenuProgDieta);

        jMenuProfissionais.setText("Profissionais   ");

        jMenuItemEF.setText("Educador Físico");
        jMenuProfissionais.add(jMenuItemEF);

        jMenuItemNutricionista.setText("Nutricionista");
        jMenuProfissionais.add(jMenuItemNutricionista);

        jMenuBarCliente.add(jMenuProfissionais);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBarCliente.add(jMenuSair);

        setJMenuBar(jMenuBarCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDesktopPaneCliente)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneCliente)
            .addComponent(jPanelCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(752, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jPanelClienteInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jPanelClienteInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelClienteInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuTabNutric;
    private javax.swing.JDesktopPane jDesktopPaneCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBarCliente;
    private javax.swing.JMenu jMenuExercicio;
    private javax.swing.JMenu jMenuGastoCaloria;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemEF;
    private javax.swing.JMenuItem jMenuItemExercAnaer;
    private javax.swing.JMenuItem jMenuItemNutricionista;
    private javax.swing.JMenu jMenuProfissionais;
    private javax.swing.JMenu jMenuProgDieta;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JLabel lblIconUser;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblMensagemIcon;
    private javax.swing.JLabel lblTreino;
    private javax.swing.JLabel lblTreinoImagem;
    public static javax.swing.JLabel lblUserNome;
    public static javax.swing.JLabel lblUserNome1;
    // End of variables declaration//GEN-END:variables
}
