/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.acorde.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Freetech
 */
public class TelaPrincipalNutricionista extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalNutricionista
     */
    public TelaPrincipalNutricionista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNomeNutric = new javax.swing.JLabel();
        lblIconUser = new javax.swing.JLabel();
        lblIconMsg = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelTelaNutricionista = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTabelaNutricional = new javax.swing.JMenu();
        jMenuDieta = new javax.swing.JMenu();
        jMenuItemDietacadastrar = new javax.swing.JMenuItem();
        jMenuItemDietaConsultar = new javax.swing.JMenuItem();
        jMenuItemDietaExcluir = new javax.swing.JMenuItem();
        jMenuAlimento = new javax.swing.JMenu();
        jMenuItemAlimentoCad = new javax.swing.JMenuItem();
        jMenuItemAlimentoConsul = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(717, 400));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblNomeNutric.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeNutric.setText("Nome");

        lblIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/user.png"))); // NOI18N

        lblIconMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/msg.png"))); // NOI18N

        lblMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMsg.setText("Mensagem");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/alimento.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Alimentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIconUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNomeNutric, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIconMsg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(21, 21, 21))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMsg)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconUser)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblNomeNutric)))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconMsg)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMsg)
                    .addComponent(jLabel2))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jPanelTelaNutricionista.setPreferredSize(new java.awt.Dimension(506, 306));

        javax.swing.GroupLayout jPanelTelaNutricionistaLayout = new javax.swing.GroupLayout(jPanelTelaNutricionista);
        jPanelTelaNutricionista.setLayout(jPanelTelaNutricionistaLayout);
        jPanelTelaNutricionistaLayout.setHorizontalGroup(
            jPanelTelaNutricionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        jPanelTelaNutricionistaLayout.setVerticalGroup(
            jPanelTelaNutricionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuTabelaNutricional.setText("Tabela Nutricional   ");
        jMenuBar1.add(jMenuTabelaNutricional);

        jMenuDieta.setText("Dieta   ");

        jMenuItemDietacadastrar.setText("Cadastrar");
        jMenuItemDietacadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDietacadastrarActionPerformed(evt);
            }
        });
        jMenuDieta.add(jMenuItemDietacadastrar);

        jMenuItemDietaConsultar.setText("Consultar");
        jMenuDieta.add(jMenuItemDietaConsultar);

        jMenuItemDietaExcluir.setText("Excluir");
        jMenuDieta.add(jMenuItemDietaExcluir);

        jMenuBar1.add(jMenuDieta);

        jMenuAlimento.setText("Alimentos   ");

        jMenuItemAlimentoCad.setText("Cadastrar");
        jMenuItemAlimentoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlimentoCadActionPerformed(evt);
            }
        });
        jMenuAlimento.add(jMenuItemAlimentoCad);

        jMenuItemAlimentoConsul.setText("Consultar");
        jMenuItemAlimentoConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlimentoConsulActionPerformed(evt);
            }
        });
        jMenuAlimento.add(jMenuItemAlimentoConsul);

        jMenuBar1.add(jMenuAlimento);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTelaNutricionista, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTelaNutricionista, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(733, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDietacadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDietacadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDietacadastrarActionPerformed

    private void jMenuItemAlimentoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlimentoCadActionPerformed
        TelaCadastroAlimento telaCadastroAlimento = new  TelaCadastroAlimento();
        telaCadastroAlimento.setVisible(true);
       jPanelTelaNutricionista.add(telaCadastroAlimento);
    }//GEN-LAST:event_jMenuItemAlimentoCadActionPerformed

    private void jMenuItemAlimentoConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlimentoConsulActionPerformed
        TelaConsultaAlimento telaConsultaAlimento = new  TelaConsultaAlimento();
        telaConsultaAlimento.setVisible(true);
       jPanelTelaNutricionista.add(telaConsultaAlimento);
    }//GEN-LAST:event_jMenuItemAlimentoConsulActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
       int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalNutricionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalNutricionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalNutricionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalNutricionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalNutricionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuAlimento;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDieta;
    private javax.swing.JMenuItem jMenuItemAlimentoCad;
    private javax.swing.JMenuItem jMenuItemAlimentoConsul;
    private javax.swing.JMenuItem jMenuItemDietaConsultar;
    private javax.swing.JMenuItem jMenuItemDietaExcluir;
    private javax.swing.JMenuItem jMenuItemDietacadastrar;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuTabelaNutricional;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTelaNutricionista;
    private javax.swing.JLabel lblIconMsg;
    private javax.swing.JLabel lblIconUser;
    private javax.swing.JLabel lblMsg;
    public static javax.swing.JLabel lblNomeNutric;
    // End of variables declaration//GEN-END:variables
}
