
package br.com.acorde.view;

public class TelaClienteDieta extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaClienteDieta
     */
    public TelaClienteDieta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelCafeManha = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelAlmoço = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelJanta = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelLancheNoite = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelLancheManha = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelLancheTarde = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Dieta");
        setMinimumSize(new java.awt.Dimension(755, 511));
        setPreferredSize(new java.awt.Dimension(755, 511));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setMinimumSize(new java.awt.Dimension(736, 88));
        jPanel2.setPreferredSize(new java.awt.Dimension(736, 88));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Dieta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanelCafeManha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCafeManhaMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Café da Manhã");

        javax.swing.GroupLayout jPanelCafeManhaLayout = new javax.swing.GroupLayout(jPanelCafeManha);
        jPanelCafeManha.setLayout(jPanelCafeManhaLayout);
        jPanelCafeManhaLayout.setHorizontalGroup(
            jPanelCafeManhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCafeManhaLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanelCafeManhaLayout.setVerticalGroup(
            jPanelCafeManhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCafeManhaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(40, 40, 40))
        );

        jPanelAlmoço.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAlmoçoMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Almoço");

        javax.swing.GroupLayout jPanelAlmoçoLayout = new javax.swing.GroupLayout(jPanelAlmoço);
        jPanelAlmoço.setLayout(jPanelAlmoçoLayout);
        jPanelAlmoçoLayout.setHorizontalGroup(
            jPanelAlmoçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlmoçoLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAlmoçoLayout.setVerticalGroup(
            jPanelAlmoçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlmoçoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanelJanta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelJantaMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Janta");

        javax.swing.GroupLayout jPanelJantaLayout = new javax.swing.GroupLayout(jPanelJanta);
        jPanelJanta.setLayout(jPanelJantaLayout);
        jPanelJantaLayout.setHorizontalGroup(
            jPanelJantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJantaLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelJantaLayout.setVerticalGroup(
            jPanelJantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJantaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanelLancheNoite.setPreferredSize(new java.awt.Dimension(280, 68));
        jPanelLancheNoite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLancheNoiteMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Lanche da Noite");

        javax.swing.GroupLayout jPanelLancheNoiteLayout = new javax.swing.GroupLayout(jPanelLancheNoite);
        jPanelLancheNoite.setLayout(jPanelLancheNoiteLayout);
        jPanelLancheNoiteLayout.setHorizontalGroup(
            jPanelLancheNoiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLancheNoiteLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel7)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanelLancheNoiteLayout.setVerticalGroup(
            jPanelLancheNoiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLancheNoiteLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLancheManha.setPreferredSize(new java.awt.Dimension(280, 68));
        jPanelLancheManha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLancheManhaMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Lanche da Manhã");

        javax.swing.GroupLayout jPanelLancheManhaLayout = new javax.swing.GroupLayout(jPanelLancheManha);
        jPanelLancheManha.setLayout(jPanelLancheManhaLayout);
        jPanelLancheManhaLayout.setHorizontalGroup(
            jPanelLancheManhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLancheManhaLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel3)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanelLancheManhaLayout.setVerticalGroup(
            jPanelLancheManhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLancheManhaLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(42, 42, 42))
        );

        jPanelLancheTarde.setPreferredSize(new java.awt.Dimension(280, 68));
        jPanelLancheTarde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLancheTardeMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Lanche da Tarde");

        javax.swing.GroupLayout jPanelLancheTardeLayout = new javax.swing.GroupLayout(jPanelLancheTarde);
        jPanelLancheTarde.setLayout(jPanelLancheTardeLayout);
        jPanelLancheTardeLayout.setHorizontalGroup(
            jPanelLancheTardeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLancheTardeLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel6)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanelLancheTardeLayout.setVerticalGroup(
            jPanelLancheTardeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLancheTardeLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelJanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAlmoço, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCafeManha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelLancheManha, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelLancheTarde, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelLancheNoite, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCafeManha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLancheManha, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelAlmoço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jPanelJanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelLancheTarde, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelLancheNoite, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelCafeManhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCafeManhaMouseClicked
        TelaDietaCafeManha cafeManha = new TelaDietaCafeManha();
        cafeManha.setVisible(true);
    }//GEN-LAST:event_jPanelCafeManhaMouseClicked

    private void jPanelAlmoçoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlmoçoMouseClicked
        TelaDietaAlmoco almoco = new TelaDietaAlmoco();
        almoco.setVisible(true);
    }//GEN-LAST:event_jPanelAlmoçoMouseClicked

    private void jPanelJantaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelJantaMouseClicked
         TelaDietaJanta janta = new TelaDietaJanta();
         janta.setVisible(true);
    }//GEN-LAST:event_jPanelJantaMouseClicked

    private void jPanelLancheManhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLancheManhaMouseClicked
         TelaDietaLancheManha lancheManha = new TelaDietaLancheManha();
          lancheManha.setVisible(true);
    }//GEN-LAST:event_jPanelLancheManhaMouseClicked

    private void jPanelLancheTardeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLancheTardeMouseClicked
         TelaDietaLancheTarde lancheTarde = new TelaDietaLancheTarde();
         lancheTarde.setVisible(true);
    }//GEN-LAST:event_jPanelLancheTardeMouseClicked

    private void jPanelLancheNoiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLancheNoiteMouseClicked
         TelaDietaLancheNoite lancheNoite = new TelaDietaLancheNoite();
         lancheNoite.setVisible(true);
    }//GEN-LAST:event_jPanelLancheNoiteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAlmoço;
    private javax.swing.JPanel jPanelCafeManha;
    private javax.swing.JPanel jPanelJanta;
    private javax.swing.JPanel jPanelLancheManha;
    private javax.swing.JPanel jPanelLancheNoite;
    private javax.swing.JPanel jPanelLancheTarde;
    // End of variables declaration//GEN-END:variables
}
