/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.acorde.view;

import java.sql.*;
import br.com.acorde.dao.ModuloConexao;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
public class TelaLogin extends javax.swing.JFrame {
    
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    

    /**
     * Creates new form TelaLogin
     */
    
    public void logar(){
      
      //cabe um fabrica aqui? acho que cabe ein
      //dá um finally pra fechar a conexao com o bd
        if(cbPerfilLogin.getSelectedItem().equals("Cliente")){
             String sql = "select * from cliente where email = ? and senha = ?";
             try{
                pst = conexao.prepareStatement(sql);
                pst.setString(1, tfNomeLogin.getText());
                pst.setString(2, pfSenhaLogin.getText());
                //eecutando a query
                rs = pst.executeQuery();
                if(rs.next()){
                    TelaPrincipalCliente principal = new TelaPrincipalCliente();
                    principal.setVisible(true);
                    //exibe o nome do usuario
                    TelaPrincipalCliente.lblUserNome.setText(rs.getString(2));
                }else{
                    JOptionPane.showMessageDialog(null, "usuario e/ou senha invalido");
                }
             }catch(Exception e){
                 JOptionPane.showMessageDialog(null, e);
             }
        }else if(cbPerfilLogin.getSelectedItem().equals("Educador Físico")){
            String sql = "select * from educador_fisico where email = ? and senha = ?";
            try{
                pst = conexao.prepareStatement(sql);
                pst.setString(1, tfNomeLogin.getText());
                pst.setString(2, pfSenhaLogin.getText());
                //eecutando a query
                rs = pst.executeQuery();
                if(rs.next()){
                    TelaPrincipalEdFis principal = new TelaPrincipalEdFis();
                    principal.setVisible(true);
                     //exibe o nome do usuario
                    TelaPrincipalEdFis.lblNomeEdFis.setText(rs.getString(2));
                }else{
                    JOptionPane.showMessageDialog(null, "usuario e/ou senha invalido");
                }
             }catch(Exception e){
                 JOptionPane.showMessageDialog(null, e);
                 e.printStackTrace();
             }
        }else{
            String sql = "select * from nutricionista where email = ? and senha = ?";
            try{
                pst = conexao.prepareStatement(sql);
                pst.setString(1, tfNomeLogin.getText());
                pst.setString(2, pfSenhaLogin.getText());
                //eecutando a query
                rs = pst.executeQuery();
                if(rs.next()){
                    TelaPrincipalNutricionista principal = new TelaPrincipalNutricionista();
                    principal.setVisible(true);
                     //exibe o nome do usuario
                    TelaPrincipalNutricionista.lblNomeNutric.setText(rs.getString(2));
                }else{
                    JOptionPane.showMessageDialog(null, "usuario e/ou senha invalido");
                }
             }catch(Exception e){
                 JOptionPane.showMessageDialog(null, e);
             }
        }
        //fecha a tela de login
        dispose();
      
    }
    public TelaLogin() {
        initComponents();
        conexao = ModuloConexao.conexaoBanco();
        //verifica se conectou com o bd 
        //System.out.println(conexao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAcorde = new javax.swing.JLabel();
        lblNomeLogin = new javax.swing.JLabel();
        lblSenhaLogin = new javax.swing.JLabel();
        cbPerfilLogin = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        pfSenhaLogin = new javax.swing.JPasswordField();
        tfNomeLogin = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnCadastraLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login <Acorde>");
        setBackground(new java.awt.Color(255, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAcorde.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        lblAcorde.setText("<Acorde>");
        getContentPane().add(lblAcorde, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 12, -1, -1));

        lblNomeLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNomeLogin.setText("EMAIL:");
        getContentPane().add(lblNomeLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 86, 46, -1));

        lblSenhaLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSenhaLogin.setText("SENHA:");
        getContentPane().add(lblSenhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 125, 46, -1));

        cbPerfilLogin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Educador Físico", "Nutricionista" }));
        getContentPane().add(cbPerfilLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 164, 141, 31));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("PERFIL:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 172, 46, -1));

        pfSenhaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfSenhaLoginActionPerformed(evt);
            }
        });
        getContentPane().add(pfSenhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 118, 141, 28));

        tfNomeLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeLoginActionPerformed(evt);
            }
        });
        getContentPane().add(tfNomeLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 70, 140, 30));

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 108, 34));

        btnCadastraLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastraLogin.setText("Cadastre-se");
        btnCadastraLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastraLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 108, 35));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Não é cliente ainda? Clique no botão ao lado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 275, -1, -1));

        setSize(new java.awt.Dimension(446, 370));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeLoginActionPerformed

    private void pfSenhaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfSenhaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfSenhaLoginActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // chamando o metodo logar;
        logar();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCadastraLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraLoginActionPerformed
       TelaCadastro.main(null);
       dispose();
    }//GEN-LAST:event_btnCadastraLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastraLogin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cbPerfilLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAcorde;
    private javax.swing.JLabel lblNomeLogin;
    private javax.swing.JLabel lblSenhaLogin;
    private javax.swing.JPasswordField pfSenhaLogin;
    private javax.swing.JTextField tfNomeLogin;
    // End of variables declaration//GEN-END:variables
}
