/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.acorde.view;

import br.com.acorde.dao.ModuloConexao;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Freetech
 */
public class TelaPrincipalEdFis extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalEdFis
     */
   
   
    
    public TelaPrincipalEdFis() {
        initComponents();
       
    }
    
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEdFis = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblNomeEdFis1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelEdFisLateral = new javax.swing.JPanel();
        lblNomeEdFis = new javax.swing.JLabel();
        lblIconUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTreinoImagem = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuExercicio = new javax.swing.JMenu();
        jMenuItemExercAer = new javax.swing.JMenuItem();
        jMenuItemExercAnaer = new javax.swing.JMenuItem();
        jMenuTreino = new javax.swing.JMenu();
        jMenuItemCadastrarTreino = new javax.swing.JMenuItem();
        jMenuItemConsultarTreino = new javax.swing.JMenuItem();
        jMenuItemExcluirTreino = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seja bem-vindo(a) ao <Acorde!>");
        setPreferredSize(new java.awt.Dimension(741, 400));
        setResizable(false);

        jPanelEdFis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Seja bem vindo(a),");
        jPanelEdFis.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 220, 30));

        lblNomeEdFis1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNomeEdFis1.setText("Nome");
        jPanelEdFis.add(lblNomeEdFis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText(" 22 de Março de 2021");
        jPanelEdFis.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 150, 20));

        jPanelEdFisLateral.setBackground(new java.awt.Color(255, 255, 255));

        lblNomeEdFis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeEdFis.setText("Nome");

        lblIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/user.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/msg.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mensagem");

        lblTreinoImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acorde/imagens/treino.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Acompanhamento");

        javax.swing.GroupLayout jPanelEdFisLateralLayout = new javax.swing.GroupLayout(jPanelEdFisLateral);
        jPanelEdFisLateral.setLayout(jPanelEdFisLateralLayout);
        jPanelEdFisLateralLayout.setHorizontalGroup(
            jPanelEdFisLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEdFisLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEdFisLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanelEdFisLateralLayout.createSequentialGroup()
                        .addGroup(jPanelEdFisLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIconUser)
                            .addComponent(jLabel1))
                        .addGap(9, 9, 9)))
                .addGroup(jPanelEdFisLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEdFisLateralLayout.createSequentialGroup()
                        .addGroup(jPanelEdFisLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEdFisLateralLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNomeEdFis, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEdFisLateralLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEdFisLateralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTreinoImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelEdFisLateralLayout.setVerticalGroup(
            jPanelEdFisLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEdFisLateralLayout.createSequentialGroup()
                .addGroup(jPanelEdFisLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEdFisLateralLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblIconUser))
                    .addGroup(jPanelEdFisLateralLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblNomeEdFis)))
                .addGap(50, 50, 50)
                .addGroup(jPanelEdFisLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblTreinoImagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEdFisLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jMenuExercicio.setText("Exercício   ");

        jMenuItemExercAer.setText("Aeróbicos");
        jMenuItemExercAer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExercAerActionPerformed(evt);
            }
        });
        jMenuExercicio.add(jMenuItemExercAer);

        jMenuItemExercAnaer.setText("Anaeróbico");
        jMenuExercicio.add(jMenuItemExercAnaer);

        jMenuBar1.add(jMenuExercicio);

        jMenuTreino.setText("Treino   ");

        jMenuItemCadastrarTreino.setText("Cadastrar ");
        jMenuItemCadastrarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarTreinoActionPerformed(evt);
            }
        });
        jMenuTreino.add(jMenuItemCadastrarTreino);

        jMenuItemConsultarTreino.setText("Consultar");
        jMenuItemConsultarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarTreinoActionPerformed(evt);
            }
        });
        jMenuTreino.add(jMenuItemConsultarTreino);

        jMenuItemExcluirTreino.setText("Excluir");
        jMenuTreino.add(jMenuItemExcluirTreino);

        jMenuBar1.add(jMenuTreino);

        jMenuSair.setText("Sair   ");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEdFisLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelEdFis, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEdFisLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelEdFis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(785, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastrarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarTreinoActionPerformed
        //abrir o form para cadastrar teino
        TelaCadastroTreino telaCadastroTreino = new TelaCadastroTreino();
        telaCadastroTreino.setVisible(true);
        jPanelEdFis.add(telaCadastroTreino);
    }//GEN-LAST:event_jMenuItemCadastrarTreinoActionPerformed

    private void jMenuItemConsultarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarTreinoActionPerformed
        //abrir o form para consultar treino
        TelaConsultaTreino telaConsultaTreino = new TelaConsultaTreino();
        telaConsultaTreino.setVisible(true);
        jPanelEdFis.add(telaConsultaTreino);
    }//GEN-LAST:event_jMenuItemConsultarTreinoActionPerformed

    private void jMenuItemExercAerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExercAerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemExercAerActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuSairMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalEdFis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalEdFis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalEdFis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalEdFis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalEdFis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExercicio;
    private javax.swing.JMenuItem jMenuItemCadastrarTreino;
    private javax.swing.JMenuItem jMenuItemConsultarTreino;
    private javax.swing.JMenuItem jMenuItemExcluirTreino;
    private javax.swing.JMenuItem jMenuItemExercAer;
    private javax.swing.JMenuItem jMenuItemExercAnaer;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuTreino;
    private javax.swing.JPanel jPanelEdFis;
    private javax.swing.JPanel jPanelEdFisLateral;
    private javax.swing.JLabel lblIconUser;
    public static javax.swing.JLabel lblNomeEdFis;
    public static javax.swing.JLabel lblNomeEdFis1;
    private javax.swing.JLabel lblTreinoImagem;
    // End of variables declaration//GEN-END:variables
}
