
package br.com.acorde.view;

import br.com.acorde.dao.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
 
public class TelaProfissionalNutricionista extends javax.swing.JInternalFrame {
    
    //variaveis do BD
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form TelaProfissionalNutricionista
     */
    
    public void pesquisarNutri(){
        String sql = "select nome as Nome, sobrenome as Sobrenome, email as Email, idNutricionista as ID from Nutricionista where nome like ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, tfNomePesquisaNutri.getText() + "%");
            rs = pst.executeQuery();
            tblNutri.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(null, e);
             e.printStackTrace();
        }
    }
    
    //setar campos do form com os dados da tabela
    public void setarCampos(){
        int setar = tblNutri.getSelectedRow();
        tfNomeNutri.setText(tblNutri.getModel().getValueAt(setar, 0).toString());
        tfSobrenomeNutri.setText(tblNutri.getModel().getValueAt(setar, 1).toString());
        tfEmailNutri.setText(tblNutri.getModel().getValueAt(setar, 2).toString());
        tfIDNutri.setText(tblNutri.getModel().getValueAt(setar, 3).toString());
    }
    
    public TelaProfissionalNutricionista() {
        initComponents();
         conexao = ModuloConexao.conexaoBanco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNomePesquisaNutri = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNutri = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfIDNutri = new javax.swing.JTextField();
        tfNomeNutri = new javax.swing.JTextField();
        tfEmailNutri = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfSobrenomeNutri = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nome"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Nutricionista");
        setMinimumSize(new java.awt.Dimension(572, 381));
        setPreferredSize(new java.awt.Dimension(572, 381));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 11, -1, -1));

        tfNomePesquisaNutri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfNomePesquisaNutri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomePesquisaNutriKeyReleased(evt);
            }
        });
        jPanel1.add(tfNomePesquisaNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 34, 346, -1));

        tblNutri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblNutri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Sobrenome", "Email", "ID"
            }
        ));
        tblNutri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNutriMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNutri);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 490, 90));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 210, 90));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Enviar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Digite sua mensagem:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nome:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        tfIDNutri.setEditable(false);
        tfIDNutri.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfIDNutri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDNutriActionPerformed(evt);
            }
        });
        jPanel1.add(tfIDNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 40, -1));

        tfNomeNutri.setEditable(false);
        tfNomeNutri.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(tfNomeNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, -1));

        tfEmailNutri.setEditable(false);
        tfEmailNutri.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(tfEmailNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Sobrenome:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        tfSobrenomeNutri.setEditable(false);
        tfSobrenomeNutri.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(tfSobrenomeNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIDNutriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDNutriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDNutriActionPerformed

    private void tfNomePesquisaNutriKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomePesquisaNutriKeyReleased
       pesquisarNutri();
    }//GEN-LAST:event_tfNomePesquisaNutriKeyReleased

    private void tblNutriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNutriMouseClicked
        setarCampos();
    }//GEN-LAST:event_tblNutriMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tblNutri;
    private javax.swing.JTextField tfEmailNutri;
    private javax.swing.JTextField tfIDNutri;
    private javax.swing.JTextField tfNomeNutri;
    private javax.swing.JTextField tfNomePesquisaNutri;
    private javax.swing.JTextField tfSobrenomeNutri;
    // End of variables declaration//GEN-END:variables
}
