
package br.com.acorde.view;


public class TelaNutricionistaDieta extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaNutricionistaDieta
     */
    public TelaNutricionistaDieta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelLancheTarde = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpCafeManha = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelLancheManha = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelJanta = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelAlmoco = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelLancheNoite = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(753, 511));
        setPreferredSize(new java.awt.Dimension(753, 511));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setMinimumSize(new java.awt.Dimension(728, 88));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Dieta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanelLancheTarde.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelLancheTarde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLancheTardeMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Lanche da Tarde");

        javax.swing.GroupLayout jPanelLancheTardeLayout = new javax.swing.GroupLayout(jPanelLancheTarde);
        jPanelLancheTarde.setLayout(jPanelLancheTardeLayout);
        jPanelLancheTardeLayout.setHorizontalGroup(
            jPanelLancheTardeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLancheTardeLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(47, 47, 47))
        );
        jPanelLancheTardeLayout.setVerticalGroup(
            jPanelLancheTardeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLancheTardeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(41, 41, 41))
        );

        jpCafeManha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpCafeManha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpCafeManhaMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Café da Manhã");

        javax.swing.GroupLayout jpCafeManhaLayout = new javax.swing.GroupLayout(jpCafeManha);
        jpCafeManha.setLayout(jpCafeManhaLayout);
        jpCafeManhaLayout.setHorizontalGroup(
            jpCafeManhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCafeManhaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(54, 54, 54))
        );
        jpCafeManhaLayout.setVerticalGroup(
            jpCafeManhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCafeManhaLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(42, 42, 42))
        );

        jPanelLancheManha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelLancheManha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLancheManhaMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Lanche da Manhã");

        javax.swing.GroupLayout jPanelLancheManhaLayout = new javax.swing.GroupLayout(jPanelLancheManha);
        jPanelLancheManha.setLayout(jPanelLancheManhaLayout);
        jPanelLancheManhaLayout.setHorizontalGroup(
            jPanelLancheManhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLancheManhaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanelLancheManhaLayout.setVerticalGroup(
            jPanelLancheManhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLancheManhaLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(40, 40, 40))
        );

        jPanelJanta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelJanta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelJantaMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Janta");

        javax.swing.GroupLayout jPanelJantaLayout = new javax.swing.GroupLayout(jPanelJanta);
        jPanelJanta.setLayout(jPanelJantaLayout);
        jPanelJantaLayout.setHorizontalGroup(
            jPanelJantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJantaLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel6)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanelJantaLayout.setVerticalGroup(
            jPanelJantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJantaLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(40, 40, 40))
        );

        jPanelAlmoco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelAlmoco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAlmocoMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Almoço");

        javax.swing.GroupLayout jPanelAlmocoLayout = new javax.swing.GroupLayout(jPanelAlmoco);
        jPanelAlmoco.setLayout(jPanelAlmocoLayout);
        jPanelAlmocoLayout.setHorizontalGroup(
            jPanelAlmocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlmocoLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAlmocoLayout.setVerticalGroup(
            jPanelAlmocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlmocoLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(38, 38, 38))
        );

        jPanelLancheNoite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelLancheNoite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLancheNoiteMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Lanche da Noite");

        javax.swing.GroupLayout jPanelLancheNoiteLayout = new javax.swing.GroupLayout(jPanelLancheNoite);
        jPanelLancheNoite.setLayout(jPanelLancheNoiteLayout);
        jPanelLancheNoiteLayout.setHorizontalGroup(
            jPanelLancheNoiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLancheNoiteLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(50, 50, 50))
        );
        jPanelLancheNoiteLayout.setVerticalGroup(
            jPanelLancheNoiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLancheNoiteLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel7)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelAlmoco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCafeManha, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(jPanelLancheManha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLancheNoite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanelLancheTarde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelJanta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelLancheTarde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCafeManha, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLancheManha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelJanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAlmoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLancheNoite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpCafeManhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCafeManhaMouseClicked
       TelaNutriDietaCadastro dietaCadastro = new  TelaNutriDietaCadastro();
       dietaCadastro.setVisible(true);
       TelaNutriDietaCadastro.jComboBoxRefeicao.setSelectedIndex(0);
    }//GEN-LAST:event_jpCafeManhaMouseClicked

    private void jPanelLancheManhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLancheManhaMouseClicked
        TelaNutriDietaCadastro dietaCadastro = new  TelaNutriDietaCadastro();
       dietaCadastro.setVisible(true);
       TelaNutriDietaCadastro.jComboBoxRefeicao.setSelectedIndex(1);
    }//GEN-LAST:event_jPanelLancheManhaMouseClicked

    private void jPanelAlmocoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlmocoMouseClicked
        TelaNutriDietaCadastro dietaCadastro = new  TelaNutriDietaCadastro();
       dietaCadastro.setVisible(true);
       TelaNutriDietaCadastro.jComboBoxRefeicao.setSelectedIndex(2);
    }//GEN-LAST:event_jPanelAlmocoMouseClicked

    private void jPanelLancheTardeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLancheTardeMouseClicked
         TelaNutriDietaCadastro dietaCadastro = new  TelaNutriDietaCadastro();
       dietaCadastro.setVisible(true);
       TelaNutriDietaCadastro.jComboBoxRefeicao.setSelectedIndex(3);
    }//GEN-LAST:event_jPanelLancheTardeMouseClicked

    private void jPanelJantaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelJantaMouseClicked
        TelaNutriDietaCadastro dietaCadastro = new  TelaNutriDietaCadastro();
       dietaCadastro.setVisible(true);
       TelaNutriDietaCadastro.jComboBoxRefeicao.setSelectedIndex(4);
    }//GEN-LAST:event_jPanelJantaMouseClicked

    private void jPanelLancheNoiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLancheNoiteMouseClicked
        TelaNutriDietaCadastro dietaCadastro = new  TelaNutriDietaCadastro();
       dietaCadastro.setVisible(true);
       TelaNutriDietaCadastro.jComboBoxRefeicao.setSelectedIndex(5);
    }//GEN-LAST:event_jPanelLancheNoiteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAlmoco;
    private javax.swing.JPanel jPanelJanta;
    private javax.swing.JPanel jPanelLancheManha;
    private javax.swing.JPanel jPanelLancheNoite;
    private javax.swing.JPanel jPanelLancheTarde;
    private javax.swing.JPanel jpCafeManha;
    // End of variables declaration//GEN-END:variables
}
